spring:
  thymeleaf:
    cache: false
  http:
    multipart:
      maxFileSize = 10Mb
      maxRequestSize=100Mb
  profiles:
    active: @profiles.active@
  redis:
    host: 212.129.135.144
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 100
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    password: {DB_PASSWD}
###    password: 123456


fdfs:
  connect-timeout: 10000
  so-timeout: 3000
  tracker-list:
  - 212.129.135.144:22122

logging:
  level:
    com.myproject.thymeleaf: debug
  config: classpath:logback.xml
server:
  port: 8080


msg:
  push:
    queue:
      email: msg.push.queue.email
    routekey:
      email: msg.push.routekey.email
    exchange:
      email: msg.push.exchange.email