spring:
  datasource:
    dynamic:
      primary: ty
      # 多数据源的配置
      datasource:
        ty:
          url: jdbc:mysql://212.129.135.144:3306/thymeleaf?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
          username: root
          password: {DB_PASSWD}

  redis:
    database:
      shiro: 3

  rabbitmq:
    addresses: 212.129.135.144
    port: 5672
    username: test
    password: test
    # 消息确认
    # 确认消息已发送到交换机（exchange）
    publisher-confirms: true
    # 确认消息已发送到队列（queue）
    publisher-returns: true