spring:
  thymeleaf:
    cache: false
  http:
    multipart:
      maxFileSize = 10Mb
      maxRequestSize=100Mb
  profiles:
    active: @profiles.active@
  redis:
    host: 212.129.135.144
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 100
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    password: {DB_PASSWD}
###    password: 123456


ip: 212.129.135.144 # 根据自己FastDFS服务器修改
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 212.129.135.144:22122
  web-server-url: http://${ip}:8888/

logging:
  level:
    com.myproject.thymeleaf: debug
  config: classpath:logback.xml
server:
  port: 8080


msg:
  push:
    queue:
      email: msg.push.queue.email
    routekey:
      email: msg.push.routekey.email
    exchange:
      email: msg.push.exchange.email

es:
  userName: elastic
  password: 111111
  hostname: 192.168.159.129
  port: 9200